#! /bin/sh

source /home/arthur/Scripts/scripts_config

compton &
/home/arthur/Scripts/startup.sh
nitrogen --restore &
wmname LG3D &

bspc config border_width        	   10
bspc config window_gap     		       30
bspc config top_padding                50

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config focused_border_color	       	$BORDER_LIGHT
bspc config active_border_color			$BORDER_DARK
bspc config normal_border_color		       	$BORDER_DARK
bspc config presel_border_color		       	$BORDER_DARK
bspc config focused_locked_border_color		$BORDER_DARK
bspc config active_locked_border_color		$BORDER_DARK
bspc config normal_locked_border_color		$BORDER_DARK
bspc config focused_sticky_border_color		$BORDER_DARK
bspc config active_sticky_border_color		$BORDER_DARK
bspc config normal_sticky_border_color		$BORDER_DARK
bspc config focused_private_border_color	$BORDER_DARK
bspc config active_private_border_color		$BORDER_DARK
bspc config normal_private_border_color		$BORDER_DARK
bspc config urgent_border_color			    "#ae5d5d"

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a vlc floating=on
