#!/usr/bin/bash

Battery() {
	BATTERY_CHARGE=$(acpi | awk '{print $4}' | sed -e 's/,// g' -e 's/%// g')
	BATTERY_STATE=$(acpi | awk '{print $3}' | sed -e 's/,// g')
	if [ "$BATTERY_STATE" = "Charging" ]; then
		CHARGING="+"
	else
		CHARGING=" "
	fi

	# echo " $CHARGING[|| $BATTERY_CHARGE ||]$CHARGING"
	echo "$CHARGING[$BATTERY_CHARGE %]"
}

while true; do
	echo "$(Battery)"
	sleep 1;
done
