#!/usr/bin/bash

Wifi() {
	# WIFI="kayNET ////"
	ONOFF=$(iwlist wlp3s0 scanning | grep "Cell 01")
	WORKING=$(iwlist wlp3s0 scanning | grep "Cell 02")
	if [ -z "$ONOFF" ]; then
		echo "--!!--"
	elif [ -z "$WORKING" ]; then
		SSID=$(iwlist wlp3s0 scanning | grep "ESSID" | sed -e 's/ESSID:"//g' | sed -e 's/"//g' )
		QUALITY=$( iwlist wlp3s0 scanning | grep "Quality" | sed -e 's/Quality=//g' -e 's|/70  ||g' -e 's/\Signal..*//')
		QUALITYSWITCH=$((QUALITY*5/70))

		case $QUALITYSWITCH in
		[1]*)
			WIFI_RESULT="   / "
			;;
		[2]*)
			WIFI_RESULT="  // "
			;;
		[3]*)
			WIFI_RESULT=" /// "
			;;
		[4-5]*)
			WIFI_RESULT="//// "
			;;
		esac

		echo -n "$SSID $WIFI_RESULT"
	else
		echo " .... "
	fi
}

while true; do
	echo "$(Wifi)"
	sleep 1;
done
